### ISSUE TITLE
Input is not well defined 

### ISSUE THREAD

**Issue by Progi1984** [PrestaShopCorp/github-action-clean-before-deploy#7]
In file https://github.com/PrestaShopCorp/github-action-clean-before-deploy/blob/dev/action.yml#L8, it's about `paths`

But in https://github.com/PrestaShopCorp/github-action-clean-before-deploy/blob/dev/action.yml#L15, it's `path` which is used.

Giving some warning :
![image](https://user-images.githubusercontent.com/1533248/128639595-aa6aef24-81b9-4808-9eae-cf6e4cd433fe.png)

**Comment by Quetzacoalt91** [comment]
Fixed by #8. Do not hesitate to reopen if the problem still occurs.
